// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI_Final_Project.Models
{
    [Table("Buy")]
    public partial class Buy
    {
        [Key]
        public int Customer_Id { get; set; }
        public int Food_Id { get; set; }

        [ForeignKey("Customer_Id")]
        [InverseProperty("Buy")]
        public virtual Customer Customer { get; set; }
        [ForeignKey("Food_Id")]
        [InverseProperty("Buys")]
        public virtual Food Food { get; set; }
    }
}