// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI_Final_Project.Models
{
    public partial class Cleaner
    {
        public Cleaner()
        {
            Rooms = new HashSet<Room>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Phone_Number { get; set; }
        [StringLength(50)]
        public string Address { get; set; }
        public double? Salary { get; set; }

        [InverseProperty("Cleaner")]
        public virtual ICollection<Room> Rooms { get; set; }
    }
}