// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI_Final_Project.Models
{
    public partial class Contact_U
    {
        [Key]
        public int Id { get; set; }
        public int? Customer_Id { get; set; }
        public string Message { get; set; }

        [ForeignKey("Customer_Id")]
        [InverseProperty("Contact_Us")]
        public virtual Customer Customer { get; set; }
    }
}