// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI_Final_Project.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Contact_Us = new HashSet<Contact_U>();
            Revevarstions = new HashSet<Revevarstion>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(50)]
        public string Phone_Number { get; set; }
        [StringLength(50)]
        public string Notional_Number { get; set; }
        public int? Reception_Id { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50), Required]
        public string Password { get; set; }
        [NotMapped, Compare("Password"), Required]
        public string Confirm_Password { get; set; }
        [StringLength(50)]
        public string Img { get; set; }
        public bool? IsAdmin { get; set; }
        public bool? IsUser { get; set; }
        public int? National_Id { get; set; }

        [ForeignKey("National_Id")]
        [InverseProperty("Customers")]
        public virtual Nationalty National { get; set; }
        [ForeignKey("Reception_Id")]
        [InverseProperty("Customers")]
        public virtual Reception Reception { get; set; }
        [InverseProperty("Customer")]
        public virtual Buy Buy { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<Contact_U> Contact_Us { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<Revevarstion> Revevarstions { get; set; }
    }
}