// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ITI_Final_Project.Models
{
    [Table("Revevarstion")]
    public partial class Revevarstion
    {
        [Key]
        public int Reservatation_Number { get; set; }
        [Column(TypeName = "date"),Required]
        public DateTime? Reservation_Date { get; set; }
        [Column(TypeName = "date"), Required]
        public DateTime? Expiry_Date { get; set; }
        public int? Room_Number { get; set; }
        public int? Customer_Id { get; set; }

        [ForeignKey("Customer_Id")]
        [InverseProperty("Revevarstions")]
        public virtual Customer Customer { get; set; }
        [ForeignKey("Room_Number")]
        [InverseProperty("Revevarstions")]
        public virtual Room Room_NumberNavigation { get; set; }
    }
}